#!/usr/bin/env python3
"""ThinkOff concentric heart for the 8x8 WS2812B matrix.

Derived from the ThinkOff logo (thinkoff-io public/assets/images/heart.png): concentric hearts in
pale pink, hot pink, magenta, yellow, green with a white core. At 8x8 there is room for three rings
plus a two-pixel core, so ring colours are taken from the outside in and the core is white.

Writes heart-v1.json (rows of RRGGBB), heart-v1.h (uint32_t[64], row-major, top-left first) and
heart-v1-preview.png (400x400 dots on black) next to this file.
"""
import json, struct, zlib, os

HERE = os.path.dirname(os.path.abspath(__file__))
MASK = ["01100110",
        "11111111",
        "11111111",
        "11111111",
        "01111110",
        "00111100",
        "00011000",
        "00000000"]
RING = ["FF8DE6", "FF3AD6", "FF00E5", "FFC400", "74D42C", "FFFFFF"]   # outside -> inside
CORE = [(2, 3), (2, 4)]                                                 # white core pixels

mask = [[int(c) for c in r] for r in MASK]

def inside(y, x):
    return 0 <= y < 8 and 0 <= x < 8 and mask[y][x] == 1

def depth_of(y, x):
    if not mask[y][x]:
        return -1
    d = 0
    while True:
        d += 1
        for dy in range(-d, d + 1):
            for dx in range(-d, d + 1):
                if abs(dy) + abs(dx) <= d and not inside(y + dy, x + dx):
                    return d - 1

px = [["000000" if depth_of(y, x) < 0 else RING[min(depth_of(y, x), len(RING) - 1)] for x in range(8)] for y in range(8)]
for (y, x) in CORE:
    if depth_of(y, x) >= 0:
        px[y][x] = "FFFFFF"

json.dump({"name": "thinkoff-heart-v1", "rows": px}, open(os.path.join(HERE, "heart-v1.json"), "w"), indent=1)
with open(os.path.join(HERE, "heart-v1.h"), "w") as f:
    f.write("// ThinkOff concentric heart, 8x8, row-major top-left first. Generated by heart/gen.py (claudemm 2026-09-10).\n")
    f.write("static const uint32_t THINKOFF_HEART[64] = {\n")
    for y in range(8):
        f.write("  " + ", ".join("0x" + c for c in px[y]) + ",\n")
    f.write("};\n")

S = 50; W = 8 * S
def png(w, h, rows):
    raw = b"".join(b"\x00" + bytes(r) for r in rows)
    def chunk(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
rows = []
for py in range(W):
    r = bytearray()
    for pxx in range(W):
        y, x = py // S, pxx // S
        cy, cx = py % S - S / 2 + 0.5, pxx % S - S / 2 + 0.5
        c = px[y][x]
        r += bytes.fromhex(c) if (c != "000000" and cy * cy + cx * cx <= (S * 0.42) ** 2) else bytes.fromhex("0a0a0a")
    rows.append(r)
open(os.path.join(HERE, "heart-v1-preview.png"), "wb").write(png(W, W, rows))
print("wrote heart-v1.json, heart-v1.h, heart-v1-preview.png")
